services:
 base:
  build:
    context: .
    dockerfile: Dockerfile_tp4
    no_cache: true
    args:
      USERNAME: # À Compléter
      USERID:   # À Compléter
  container_name: fw1-tp4
  command: /bin/bash
  tty: true
  stdin_open: true
  volumes:
  - .:/home/user/workspace
  ports:
  - "8088:8000"
  environment:
    PS1: "[ $$(whoami) | \\w ] "